from enum import Enum

class EnviromentsEnum(Enum):
    DB_USER = "DB_USER"
    DB_PASSWORD = "DB_PASSWORD"
    DB_HOST = "DB_HOST"
    DB_PORT = "DB_PORT"
    DB_NAME = "DB_NAME"
    JWT_KEY = "JWT_KEY"
    GOOGLE_CLIENT_ID = "GOOGLE_CLIENT_ID"
    GOOGLE_CLIENT_SECRET = "GOOGLE_CLIENT_SECRET"
    GOOGLE_CALLBACK_URL = "GOOGLE_CALLBACK_URL"
    GOOGLE_MAIL_HOST="GOOGLE_MAIL_HOST"
    GOOGLE_MAIL_PORT="GOOGLE_MAIL_PORT"
    GOOGLE_MAIL_SECURE="GOOGLE_MAIL_SECURE"
    GOOGLE_MAIL_USER="GOOGLE_MAIL_USER"
    GOOGLE_MAIL_PASS="GOOGLE_MAIL_PASS"
    GOOGLE_APPLICATION_CREDENTIALS="GOOGLE_APPLICATION_CREDENTIALS"
    GOOGLE_BUCKET_NAME="GOOGLE_BUCKET_NAME"
    
class ExceptionsEnum(Enum):
    NOT_ENVIROMENT_VARIABLE_AVABLE = "No se encontro la variable de entorno :variable"